[package]
name = "replikan-activation-journal-file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
replikan-local-executor = { path = "../replikan-local-executor" }
replikan-opportunities = { path = "../replikan-opportunities" }
replikan-resource = { path = "../replikan-resource" }

[lints]
workspace = true
