[package]
name = "replikan-opportunities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
replikan-core = { path = "../replikan-core" }
replikan-economics = { path = "../replikan-economics" }

[lints]
workspace = true
